#!/usr/bin/env zsh 
echo "Creating Bucket..."

# Check for bucket name

if [ -z "$1" ]; then
echo "Error:NoBucketName"
exit 1
fi 

BUCKET_NAME=$1 



# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html

aws s3api create-bucket --bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ap-south-1" \
--output text --query Location --color auto \


if [ $? -ne 0 ]; then
    echo "Error:FailedToCreateBucket"
    exit 1
fi
