#!/usr/bin/env zsh

echo "Syncing to S3 Bucket..."

if [ -z "$1" ]; then
  echo "Error:NoBucketName"
  exit 1
fi

BUCKET_NAME="$1"
LOCAL_FOLDER="${2:-$HOME}"  # Defaults to home directory

echo "Syncing $LOCAL_FOLDER to s3://$BUCKET_NAME"

aws s3 sync $LOCAL_FOLDER s3://$BUCKET_NAME
echo "Sync complete."

if [ $? -ne 0 ]; then
  echo "Error:FailedToSyncFiles"
  exit 1
fi

